### ISSUE TITLE
Gem has been installed, but 'command not found'

### ISSUE THREAD

**Issue by ruvaleev** [alisnic/stackprof-webnav#23]
macOS Catalina, has installed gem `gem install stackprof-webnav`, but when I try to run service, I got the error
```
stackprof-webnav
-bash: stackprof-webnav: command not found
```

**Comment by alisnic** [comment]
do you use a ruby version manager, like RVM? or is the built-in Ruby from macOS?

**Comment by ruvaleev** [comment]
I use rbenv. I guess, the problem is I must use `bundle exec` for run anything. Thanks for help! )
