### ISSUE TITLE
failed to load command: stackprof-webnav due to missing pry dependency

### ISSUE THREAD

**Issue by senhalil** [alisnic/stackprof-webnav#26]
Installing stackprof-webnaw with the following Gemfile and running it with `bundle exec stackprof-webnaw` results in an error
```ruby
source 'https://rubygems.org'
ruby '~> 2.5'

# gem 'pry' # it works when this line is de-commented
gem 'stackprof-webnav'
```

I think it is because `pry` is required in `server.rb` but it is not included in the gemspec. Since it is included in the Gemfile, it is not installed automatically. 

It can be fixed by adding `pry` as a dependency in the gemspec file -- or conditionally requiring the `pry` gem only in dev mode (but this option only works if the server is launched on production mode `APP_ENV=production bundle exec stackprof-webnav`).

**Comment by alisnic** [comment]
Awesome, thanks!
